---
title: "Lab Work 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(ggplot2)
library(datasets)
library(tidyverse)
library(dplyr)
library(ggplot2)
head(mtcars)
```


```{r,echo=F,fig.width=8,fig.height=8,fig.align='center'}
mg <- ggplot(mtcars, aes(x = mpg, y = wt)) + geom_point()
mg + facet_grid(vs + am ~ gear)
```

### My solution
### Rewrite the dataframe
```{r}
for (i in 1:length(mtcars$vs))
{if (mtcars$vs[i] == 1)
{mtcars$vs[i] <- "V-engine"}
  else {mtcars$vs[i] <- "S-engine" } }

for (i in 1:length(mtcars$am))
{if (mtcars$am[i] == 1)
{mtcars$am[i] <- "Automatic"}
  else {mtcars$am[i] <- "Manual" } }

for (i in 1:length(mtcars$gear))
{if (mtcars$gear[i] == 3)
{mtcars$gear[i] <- "Gear 3"}
  else if (mtcars$gear[i] == 4)  
    {mtcars$gear[i] <- "Gear 4"}
        else  {mtcars$gear[i] <- "Gear 5"}
}  
```


## Plot
```{r,echo=F,fig.width=2,fig.height=2,fig.align='center'}

mg <- ggplot(mtcars, aes(x = mpg, y = wt, color = gear)) + geom_point()
mg + facet_grid(vs ~ am)   +
theme_bw(base_size=9) +
  xlab ("miles per gallon") +
  ylab ("weight") +
    theme (legend.position=c(0.9,0.7),
           axis.text.x = element_text (angle=30),
           legend.background=element_rect(colour=NA,fill=NA) )
```



```{r}
ds <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  geom_smooth()
```

### My Solution

```{r}
ds <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point() +
  geom_smooth(aes(color=class,fill=class)) +
  theme_bw(base_size=18) +
  xlab("Engine displacement") +
  ylab("Highway miles per gallon") 
      
ds
```



